/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ifnazar' at '10/04/17 17:53' with Gradle 2.14.1
 *
 * @author ifnazar, @date 10/04/17 17:53
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
